// Re-export the base fixture from the package
// Override or extend test/expect here if needed



































































EXECUTE FUNCTION public.touch_profiles_updated_at();FOR EACH ROWBEFORE UPDATE ON public.profilesCREATE TRIGGER trg_touch_profiles_updated_atDROP TRIGGER IF EXISTS trg_touch_profiles_updated_at ON public.profiles;$$ LANGUAGE plpgsql;END;  RETURN NEW;  NEW.updated_at = now();BEGINRETURNS trigger AS $$CREATE OR REPLACE FUNCTION public.touch_profiles_updated_at()-- Keep updated_at fresh.  ON public.profiles (lower(username));CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_unique_ci-- Uniqueness (case-insensitive).END $$;  END IF;      CHECK (username ~ '^[a-z0-9_\.\-]+$');      ADD CONSTRAINT profiles_username_format    ALTER TABLE public.profiles  ) THEN    WHERE conname = 'profiles_username_format'    SELECT 1 FROM pg_constraint  IF NOT EXISTS (  END IF;      CHECK (char_length(username) BETWEEN 3 AND 32);      ADD CONSTRAINT profiles_username_length    ALTER TABLE public.profiles  ) THEN    WHERE conname = 'profiles_username_length'    SELECT 1 FROM pg_constraint  IF NOT EXISTS (BEGINDO $$  ALTER COLUMN username SET NOT NULL;ALTER TABLE public.profiles-- Constraints: not null + basic format + reasonable length.WHERE username IS NULL OR btrim(username) = '';SET username = 'user_' || replace(user_id::text, '-', '')UPDATE public.profiles-- NOTE: This is a transitional step; app should force user to set a proper username.-- If still null/empty, backfill deterministic placeholder (stable but explicit).WHERE username IS NULL;SET username = NULLIF(regexp_replace(lower(coalesce(display_name, '')), '\s+', '_', 'g'), '')UPDATE public.profiles-- Backfill from display_name where possible (best-effort).END $$;  END IF;    ALTER TABLE public.profiles ADD COLUMN username TEXT;  ) THEN    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'username'    FROM information_schema.columns    SELECT 1  IF NOT EXISTS (  -- Add column if missing (some older schemas may not have it)BEGINDO $$export { test, expect } from "@playwright/test";
