/**
 * CallKit Capacitor Plugin — iOS native integration + web fallback.
 *
 * Architecture:
 * - On iOS (native): delegates to CXProvider / CXCallController via Swift plugin.
 * - On Web / Android (fallback): uses Notification API for incoming call alerts;
 *   non-applicable operations emit console.warn (no-op) with explicit reason.
 * - All listener events are forwarded through the existing event bridge so the
 *   legacy emitCallKitAction consumers remain compatible.
 *
 * Security notes:
 * - UUIDs must be generated by the application layer (caller-controlled),
 *   not by this plugin, to preserve idempotency and replay-detection guarantees.
 * - Notification permission is requested lazily (first incoming call).
 * - No secrets are stored or logged here.
 *
 * @see https://capacitorjs.com/docs/plugins/creating-plugins
 */

import { registerPlugin } from "@capacitor/core";
import type { PluginListenerHandle } from "@capacitor/core";

// ---------------------------------------------------------------------------
// Plugin interface
// ---------------------------------------------------------------------------

export interface CallKitPlugin {
  /** Report an incoming call to the system. On iOS shows the native incoming call UI. */
  reportIncomingCall(options: {
    uuid: string;
    handle: string;
    displayName: string;
    hasVideo: boolean;
  }): Promise<void>;

  /** Start an outgoing call. On iOS updates Call Directory and CXCallController. */
  startCall(options: {
    uuid: string;
    handle: string;
    displayName: string;
    hasVideo: boolean;
  }): Promise<void>;

  /** End an active call. */
  endCall(options: { uuid: string }): Promise<void>;

  /** Update mute state of an active call. */
  setMuted(options: { uuid: string; muted: boolean }): Promise<void>;

  /** Put a call on hold or resume from hold. */
  setHeld(options: { uuid: string; held: boolean }): Promise<void>;

  /** Register a listener for CallKit delegate events. */
  addListener(
    event: "callAnswered" | "callEnded" | "callStarted" | "setMuted" | "setHeld",
    handler: (data: CallKitEvent) => void,
  ): Promise<PluginListenerHandle>;

  /** Remove all registered listeners. */
  removeAllListeners(): Promise<void>;
}

export interface CallKitEvent {
  uuid: string;
  /** Present only for setMuted event */
  muted?: boolean;
  /** Present only for setHeld event */
  held?: boolean;
}

// ---------------------------------------------------------------------------
// Web fallback implementation
// ---------------------------------------------------------------------------

/** Notifications permission cache — requested once per session. */
let _notifPermissionRequested = false;

async function ensureNotificationPermission(): Promise<boolean> {
  if (typeof Notification === "undefined") return false;
  if (_notifPermissionRequested) return Notification.permission === "granted";
  _notifPermissionRequested = true;
  const result = await Notification.requestPermission();
  return result === "granted";
}

/** Internal event bus for web fallback — mirrors native delegate callbacks. */
const _webListeners: Map<string, Set<(data: CallKitEvent) => void>> = new Map();

function _dispatchWebEvent(event: string, data: CallKitEvent): void {
  const handlers = _webListeners.get(event);
  if (handlers) {
    for (const handler of handlers) {
      try {
        handler(data);
      } catch (err) {
        console.error("[CallKit:web] listener error", event, err);
      }
    }
  }
  // Also forward through legacy action bridge for backward compatibility
  if (typeof window !== "undefined") {
    window.dispatchEvent(
      new CustomEvent("mansoni:native-call-action", {
        detail: { type: event, ...data },
      }),
    );
  }
}

/** Web fallback — shown when `@capacitor/core` cannot find a native plugin. */
const CallKitWebFallback: CallKitPlugin = {
  async reportIncomingCall({ uuid, displayName, hasVideo }) {
    const permitted = await ensureNotificationPermission();
    if (permitted) {
      new Notification(`Incoming ${hasVideo ? "video" : "audio"} call`, {
        body: displayName,
        tag: `callkit-incoming-${uuid}`,
        requireInteraction: true,
        silent: false,
      });
    }
    // Simulate auto-notify of "callStarted" for web testing; real answer comes from UI
    console.info("[CallKit:web] reportIncomingCall", { uuid, displayName, hasVideo });
  },

  async startCall({ uuid, displayName, hasVideo }) {
    console.warn("[CallKit:web] startCall — no native CallKit on this platform", {
      uuid,
      displayName,
      hasVideo,
    });
  },

  async endCall({ uuid }) {
    // Dismiss notification if it exists
    if (typeof Notification !== "undefined") {
      // Service Worker notification dismissal would go here in a full PWA implementation
    }
    console.info("[CallKit:web] endCall", { uuid });
    _dispatchWebEvent("callEnded", { uuid });
  },

  async setMuted({ uuid, muted }) {
    console.warn("[CallKit:web] setMuted — no native CallKit on this platform", { uuid, muted });
  },

  async setHeld({ uuid, held }) {
    console.warn("[CallKit:web] setHeld — no native CallKit on this platform", { uuid, held });
  },

  async addListener(event, handler) {
    if (!_webListeners.has(event)) {
      _webListeners.set(event, new Set());
    }
    _webListeners.get(event)!.add(handler);
    return {
      remove: async () => {
        _webListeners.get(event)?.delete(handler);
      },
    };
  },

  async removeAllListeners() {
    _webListeners.clear();
  },
};

// ---------------------------------------------------------------------------
// Plugin registration
// ---------------------------------------------------------------------------

/**
 * The registered Capacitor plugin. On iOS with the native Swift plugin installed,
 * this delegates to CXProvider. On all other platforms, `CallKitWebFallback` runs.
 */
export const CallKit = registerPlugin<CallKitPlugin>("CallKit", {
  web: () => CallKitWebFallback,
});

// ---------------------------------------------------------------------------
// Legacy event bridge (backward compatibility)
// ---------------------------------------------------------------------------

export type CallKitAction =
  | { type: "incoming"; callId: string; callerName: string; hasVideo: boolean }
  | { type: "accept"; callId: string }
  | { type: "decline"; callId: string }
  | { type: "end"; callId: string; reason?: string };

type CallKitListener = (action: CallKitAction) => void;

const _legacyListeners = new Set<CallKitListener>();

export function onCallKitAction(listener: CallKitListener): () => void {
  _legacyListeners.add(listener);
  return () => _legacyListeners.delete(listener);
}

export function emitCallKitAction(action: CallKitAction): void {
  for (const listener of _legacyListeners) {
    listener(action);
  }
  if (typeof window !== "undefined") {
    window.dispatchEvent(
      new CustomEvent("mansoni:native-call-action", { detail: action }),
    );
  }
}
