/**
 * Android ConnectionService Capacitor Plugin + web fallback.
 *
 * Architecture:
 * - On Android (native): delegates to Android Telecom ConnectionService API via Java plugin.
 * - On Web / iOS (fallback): uses Notification API for incoming call alerts;
 *   non-applicable operations emit console.warn (no-op) with explicit reason.
 * - All listener events are forwarded through the existing event bridge for
 *   backward compatibility with legacy `onConnectionServiceAction` consumers.
 *
 * Security notes:
 * - UUIDs must be generated by the application layer (idempotency + replay-detection).
 * - Notification permission requested lazily on first incoming call.
 * - No credentials or tokens are stored or logged here.
 */

import { registerPlugin } from "@capacitor/core";
import type { PluginListenerHandle } from "@capacitor/core";

// ---------------------------------------------------------------------------
// Plugin interface
// ---------------------------------------------------------------------------

export interface ConnectionServicePlugin {
  /** Report an incoming call to Android Telecom. Shows system incoming call UI. */
  reportIncomingCall(options: {
    uuid: string;
    handle: string;
    displayName: string;
    hasVideo: boolean;
  }): Promise<void>;

  /** Accept an incoming call (e.g., after user taps Answer in app UI). */
  acceptCall(options: { uuid: string }): Promise<void>;

  /** Reject an incoming call. */
  rejectCall(options: { uuid: string }): Promise<void>;

  /** End an active call. */
  endCall(options: { uuid: string }): Promise<void>;

  /** Update mute state on an active connection. */
  setMuted(options: { uuid: string; muted: boolean }): Promise<void>;

  /** Register a listener for ConnectionService events from the OS. */
  addListener(
    event: "callAnswered" | "callRejected" | "callEnded" | "setMuted",
    handler: (data: ConnectionServiceEvent) => void,
  ): Promise<PluginListenerHandle>;

  /** Remove all registered listeners. */
  removeAllListeners(): Promise<void>;
}

export interface ConnectionServiceEvent {
  uuid: string;
  /** Present only for setMuted event */
  muted?: boolean;
}

// ---------------------------------------------------------------------------
// Web fallback implementation
// ---------------------------------------------------------------------------

let _notifPermissionRequested = false;

async function ensureNotificationPermission(): Promise<boolean> {
  if (typeof Notification === "undefined") return false;
  if (_notifPermissionRequested) return Notification.permission === "granted";
  _notifPermissionRequested = true;
  const result = await Notification.requestPermission();
  return result === "granted";
}

const _webListeners: Map<string, Set<(data: ConnectionServiceEvent) => void>> = new Map();

function _dispatchWebEvent(event: string, data: ConnectionServiceEvent): void {
  const handlers = _webListeners.get(event);
  if (handlers) {
    for (const handler of handlers) {
      try {
        handler(data);
      } catch (err) {
        console.error("[ConnectionService:web] listener error", event, err);
      }
    }
  }
  if (typeof window !== "undefined") {
    window.dispatchEvent(
      new CustomEvent("mansoni:native-call-action", {
        detail: { type: event, ...data },
      }),
    );
  }
}

const ConnectionServiceWebFallback: ConnectionServicePlugin = {
  async reportIncomingCall({ uuid, displayName, hasVideo }) {
    const permitted = await ensureNotificationPermission();
    if (permitted) {
      new Notification(`Incoming ${hasVideo ? "video" : "audio"} call`, {
        body: displayName,
        tag: `connection-service-incoming-${uuid}`,
        requireInteraction: true,
        silent: false,
      });
    }
    console.info("[ConnectionService:web] reportIncomingCall", { uuid, displayName, hasVideo });
  },

  async acceptCall({ uuid }) {
    console.info("[ConnectionService:web] acceptCall", { uuid });
    _dispatchWebEvent("callAnswered", { uuid });
  },

  async rejectCall({ uuid }) {
    console.info("[ConnectionService:web] rejectCall", { uuid });
    _dispatchWebEvent("callRejected", { uuid });
  },

  async endCall({ uuid }) {
    console.info("[ConnectionService:web] endCall", { uuid });
    _dispatchWebEvent("callEnded", { uuid });
  },

  async setMuted({ uuid, muted }) {
    console.warn("[ConnectionService:web] setMuted — no native ConnectionService on this platform", {
      uuid,
      muted,
    });
  },

  async addListener(event, handler) {
    if (!_webListeners.has(event)) {
      _webListeners.set(event, new Set());
    }
    _webListeners.get(event)!.add(handler);
    return {
      remove: async () => {
        _webListeners.get(event)?.delete(handler);
      },
    };
  },

  async removeAllListeners() {
    _webListeners.clear();
  },
};

// ---------------------------------------------------------------------------
// Plugin registration
// ---------------------------------------------------------------------------

/**
 * The registered Capacitor plugin. On Android with the native Java plugin installed,
 * this delegates to Android Telecom ConnectionService. On all other platforms,
 * `ConnectionServiceWebFallback` runs.
 */
export const ConnectionService = registerPlugin<ConnectionServicePlugin>(
  "ConnectionService",
  {
    web: () => ConnectionServiceWebFallback,
  },
);

// ---------------------------------------------------------------------------
// Legacy event bridge (backward compatibility)
// ---------------------------------------------------------------------------

export type ConnectionServiceAction =
  | { type: "incoming"; callId: string; callerName: string; hasVideo: boolean }
  | { type: "answer"; callId: string }
  | { type: "reject"; callId: string }
  | { type: "disconnect"; callId: string; reason?: string };

type ConnectionServiceListener = (action: ConnectionServiceAction) => void;

const _legacyListeners = new Set<ConnectionServiceListener>();

export function onConnectionServiceAction(listener: ConnectionServiceListener): () => void {
  _legacyListeners.add(listener);
  return () => _legacyListeners.delete(listener);
}

export function emitConnectionServiceAction(action: ConnectionServiceAction): void {
  for (const listener of _legacyListeners) {
    listener(action);
  }
  if (typeof window !== "undefined") {
    window.dispatchEvent(
      new CustomEvent("mansoni:native-call-action", { detail: action }),
    );
  }
}
