param(
  [string]$AuditJsonPath = "",
  [string]$OutputDir = "",
  [string]$SecurityDefinerAllowlistPath = "",
  [string]$RlsExemptTablesPath = "",
  [string]$TruePolicyAllowlistPath = ""
)

$ErrorActionPreference = 'Stop'

function Read-Allowlist([string]$Path) {
  if ([string]::IsNullOrWhiteSpace($Path) -or -not (Test-Path -LiteralPath $Path)) {
    return (New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase))
  }

  $set = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
  Get-Content -LiteralPath $Path -Encoding UTF8 | ForEach-Object {
    $line = [string]$_
    if ($line.Contains('#')) {
      $line = $line.Substring(0, $line.IndexOf('#'))
    }
    $line = $line.Trim()
    if (-not [string]::IsNullOrWhiteSpace($line)) {
      [void]$set.Add($line)
    }
  }
  return $set
}

function Test-InSet($Set, [string]$Value) {
  if ($null -eq $Set) { return $false }
  if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
  try {
    return $Set.Contains($Value)
  } catch {
    return $false
  }
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

if ([string]::IsNullOrWhiteSpace($AuditJsonPath)) {
  $AuditJsonPath = Join-Path $repoRoot 'tmp\security\generated\critical-audit.json'
}
if (-not (Test-Path -LiteralPath $AuditJsonPath)) {
  throw "Audit JSON not found: $AuditJsonPath"
}

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
  $OutputDir = Join-Path $repoRoot 'tmp\security\generated'
}
if (-not (Test-Path -LiteralPath $OutputDir)) {
  New-Item -Path $OutputDir -ItemType Directory -Force | Out-Null
}

if ([string]::IsNullOrWhiteSpace($SecurityDefinerAllowlistPath)) {
  $SecurityDefinerAllowlistPath = Join-Path $repoRoot 'scripts\security\allowlists\security-definer-execute-allowlist.txt'
}
if ([string]::IsNullOrWhiteSpace($RlsExemptTablesPath)) {
  $RlsExemptTablesPath = Join-Path $repoRoot 'scripts\security\allowlists\public-rls-exempt-tables.txt'
}
if ([string]::IsNullOrWhiteSpace($TruePolicyAllowlistPath)) {
  $TruePolicyAllowlistPath = Join-Path $repoRoot 'scripts\security\allowlists\true-policy-allowlist.txt'
}

$sdAllow = Read-Allowlist -Path $SecurityDefinerAllowlistPath
$rlsExempt = Read-Allowlist -Path $RlsExemptTablesPath
$policyAllow = Read-Allowlist -Path $TruePolicyAllowlistPath

$audit = Get-Content -LiteralPath $AuditJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
$sdFunctions = @($audit.details.security_definer_functions)
$rlsDisabled = @($audit.details.public_tables_rls_disabled)
$truePolicies = @($audit.details.true_policies)
$sendMessageSigs = @($audit.details.send_message_v1_signatures)

$generatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ssZ')

# 1) SECURITY DEFINER lockdown SQL.
$sdLines = New-Object System.Collections.Generic.List[string]
$sdLines.Add('-- Generated by scripts/security/supabase-generate-hardening-sql.ps1')
$sdLines.Add("-- Generated at: $generatedAt")
$sdLines.Add('-- Phase: Restrict SECURITY DEFINER execute surface to service_role by default.')
$sdLines.Add('')

$sdTargets = @($sdFunctions | Where-Object {
  if ($null -eq $_) { return $false }
  if ([string]::IsNullOrWhiteSpace([string]$_.signature)) { return $false }
  (($_.anon_exec -eq $true) -or ($_.authenticated_exec -eq $true)) -and
  (-not (Test-InSet -Set $sdAllow -Value ([string]$_.signature)))
})

if ($sdTargets.Count -eq 0) {
  $sdLines.Add('-- No SECURITY DEFINER execute revocations needed after allowlist filtering.')
} else {
  foreach ($fn in $sdTargets) {
    $sig = [string]$fn.signature
    $sdLines.Add("revoke all on function $sig from public;")
    $sdLines.Add("revoke all on function $sig from anon;")
    $sdLines.Add("revoke all on function $sig from authenticated;")
    $sdLines.Add("grant execute on function $sig to service_role;")
    $sdLines.Add('')
  }
}

$sdPath = Join-Path $OutputDir '01_restrict_security_definer.sql'
Set-Content -LiteralPath $sdPath -Encoding UTF8 -Value $sdLines

# 2) Enable RLS for all non-exempt public tables currently disabled.
$rlsLines = New-Object System.Collections.Generic.List[string]
$rlsLines.Add('-- Generated by scripts/security/supabase-generate-hardening-sql.ps1')
$rlsLines.Add("-- Generated at: $generatedAt")
$rlsLines.Add('-- Phase: Enable RLS for public tables currently without RLS.')
$rlsLines.Add('')

$rlsTargets = @($rlsDisabled | Where-Object {
  if ($null -eq $_) { return $false }
  if ([string]::IsNullOrWhiteSpace([string]$_.schema_name) -or [string]::IsNullOrWhiteSpace([string]$_.table_name)) { return $false }
  $fullName = "$($_.schema_name).$($_.table_name)"
  -not (Test-InSet -Set $rlsExempt -Value $fullName)
})

if ($rlsTargets.Count -eq 0) {
  $rlsLines.Add('-- No RLS enable statements needed after exempt table filtering.')
} else {
  foreach ($t in $rlsTargets) {
    $schemaName = [string]$t.schema_name
    $tableName = [string]$t.table_name
    $rlsLines.Add("alter table if exists `"$schemaName`".`"$tableName`" enable row level security;")
  }
}

$rlsPath = Join-Path $OutputDir '02_enable_rls_public_tables.sql'
Set-Content -LiteralPath $rlsPath -Encoding UTF8 -Value $rlsLines

# 3) True-policy review SQL (drop candidates not allowlisted).
$policyLines = New-Object System.Collections.Generic.List[string]
$policyLines.Add('-- Generated by scripts/security/supabase-generate-hardening-sql.ps1')
$policyLines.Add("-- Generated at: $generatedAt")
$policyLines.Add('-- Phase: Drop policies with bare true predicates unless allowlisted.')
$policyLines.Add('-- IMPORTANT: review before apply.')
$policyLines.Add('')

$policyTargets = @($truePolicies | Where-Object {
  if ($null -eq $_) { return $false }
  if ([string]::IsNullOrWhiteSpace([string]$_.schema_name) -or [string]::IsNullOrWhiteSpace([string]$_.table_name) -or [string]::IsNullOrWhiteSpace([string]$_.policy_name)) { return $false }
  $key = "$($_.schema_name).$($_.table_name).$($_.policy_name)"
  -not (Test-InSet -Set $policyAllow -Value $key)
})

if ($policyTargets.Count -eq 0) {
  $policyLines.Add('-- No true-policy drop statements needed after allowlist filtering.')
} else {
  foreach ($p in $policyTargets) {
    $schemaName = [string]$p.schema_name
    $tableName = [string]$p.table_name
    $policyName = ([string]$p.policy_name).Replace('"', '""')
    $policyLines.Add("drop policy if exists `"$policyName`" on `"$schemaName`".`"$tableName`";")
  }
}

$policyPath = Join-Path $OutputDir '03_drop_true_policies_candidates.sql'
Set-Content -LiteralPath $policyPath -Encoding UTF8 -Value $policyLines

# 4) send_message_v1 canonicalization template.
$sendLines = New-Object System.Collections.Generic.List[string]
$sendLines.Add('-- Generated by scripts/security/supabase-generate-hardening-sql.ps1')
$sendLines.Add("-- Generated at: $generatedAt")
$sendLines.Add('-- Phase: Canonicalize send_message_v1 signature.')
$sendLines.Add('-- Keep only 4-arg signature and provide optional compatibility wrapper if required.')
$sendLines.Add('')

$sendLines.Add('-- Existing signatures observed:')
foreach ($s in $sendMessageSigs) {
  $sendLines.Add("-- - $($s.signature)")
}
$sendLines.Add('')

$sendLines.Add('-- Example plan (edit body to your canonical implementation):')
$sendLines.Add('drop function if exists public.send_message_v1(uuid, uuid, text);')
$sendLines.Add('-- Keep canonical 4-arg function implementation:')
$sendLines.Add('-- create or replace function public.send_message_v1(conversation_id uuid, client_msg_id uuid, body text, is_silent boolean)')
$sendLines.Add('-- returns table(id uuid, conversation_id uuid, sender_id uuid, body text, created_at timestamptz, seq bigint)')
$sendLines.Add('-- language plpgsql security definer set search_path = public as $$')
$sendLines.Add('-- begin')
$sendLines.Add('--   -- canonical body')
$sendLines.Add('-- end;')
$sendLines.Add('-- $$;')
$sendLines.Add('revoke all on function public.send_message_v1(uuid, uuid, text, boolean) from public;')
$sendLines.Add('grant execute on function public.send_message_v1(uuid, uuid, text, boolean) to authenticated;')

$sendPath = Join-Path $OutputDir '04_send_message_v1_canonicalization_template.sql'
Set-Content -LiteralPath $sendPath -Encoding UTF8 -Value $sendLines

Write-Host "Generated SQL files:" -ForegroundColor Green
Write-Host " - $sdPath"
Write-Host " - $rlsPath"
Write-Host " - $policyPath"
Write-Host " - $sendPath"

exit 0
