// Группировка таблиц Supabase types

const tables = `ab_assignments
ab_experiments
achievement_badges
ad_campaigns
ad_creative_history
ad_creatives
ad_impressions
add_yours_chains
add_yours_entries
admin_action_log
admin_audit_events
admin_kill_switches
admin_permissions
admin_policies
admin_role_permissions
admin_roles
admin_sessions
admin_staff_profiles
admin_user_roles
admin_users
agency_reviews
agent_profiles
ai_chat_messages
ai_feedback
ai_stickers
ai_usage_limits
algorithm_versions
anonymous_admin_actions
anti_abuse_policies
anti_abuse_weights
app_icon_catalog
appeal_rate_limits
approval_steps
approvals
archived_posts
archived_stories
aria_memories
assets
audio_room_participants
audio_rooms
audio_tracks
audit_hash_anchors
auth_accounts
auth_audit_events
auth_devices
auth_sessions
authorized_sites
blocked_users
boosted_posts
bot_analytics
bot_chats
bot_commands
bot_conversations
bot_inline_keyboards
bot_messages
bot_payment_providers
bot_tokens
bot_update_events
bot_webhooks
bots
branded_content_approved_authors
branded_content_partner_requests
broadcast_channel_members
broadcast_channel_messages
broadcast_channels
business_accounts
business_chat_labels
calls
channel_analytics_daily
channel_audit_log
channel_boost_levels
channel_boosts
channel_capability_catalog
channel_capability_overrides
channel_invite_links
channel_join_requests
channel_members
channel_message_reactions
channel_message_views
channel_messages
channel_moderation_log
channel_pins
channel_post_stats
channel_post_view_log
channel_role_capabilities
channel_user_settings
channels
chat_client_metrics
chat_encryption_keys
chat_events
chat_folder_items
chat_folders
chat_inbox_projection
chat_rate_limits
chat_receipts
chat_recovery_throttle
chat_shortcuts
chat_stream_heads
chat_write_ledger
close_friends
collectible_usernames
comment_likes
comments
content_drafts
content_filters
content_flags
content_moderation_actions
content_moderation_status
content_reports
controversial_content_flags
conversation_cursors
conversation_participants
conversation_pins
conversation_state
conversations
coordinated_behavior_clusters
core_events
core_receipts
core_scope_members
core_scopes
coupon_usages
coupons
creator_earnings
creator_fund_accounts
creator_fund_daily_earnings
creator_fund_payouts
creator_metrics
creator_metrics_snapshots
creator_subscriptions
custom_emojis
dating_matches
dating_profiles
dating_swipes
decision_engine_events
decision_jobs
decision_snapshots
delegation_tokens
delegations
delivery_outbox
device_accounts
device_active_account
device_tokens
dm_pairs
draft_versions
drafts
edge_rate_limits
editor_assets
editor_clips
editor_effects
editor_keyframes
editor_projects
editor_templates
editor_tracks
email_deliveries
email_imap_settings
email_inbox
email_otp_codes
email_outbox
email_smtp_settings
email_templates
email_threads
emergency_signals
emoji_packs
emoji_sets
explore_cache
explore_cache_entries
explore_section_clicks
explore_sessions
feature_flags
feed_impressions
feed_quality_metrics
follow_requests
followers
gift_catalog
group_chat_members
group_chat_messages
group_chat_slow_mode_state
group_chats
group_invite_links
group_members
group_message_reads
group_topics
guardrail_alerts
guardrails_config
guide_items
guides
hashtag_categories
hashtag_category_mapping
hashtag_status_changes
hashtags
highlight_stories
highlights
idempotency_keys
idempotency_locks
idempotency_outcomes_archive
idempotency_outcomes_hot
idempotency_register
incidents
insurance_calculations
insurance_claims
insurance_clients
insurance_commissions
insurance_companies
insurance_company_reviews
insurance_drafts
insurance_kbm_cache
insurance_loyalty_history
insurance_payments
insurance_payouts
insurance_policies
insurance_products
insurance_provider_logs
insurance_providers
insurance_quote_offers
insurance_quote_sessions
insurance_referral_links
insurance_vehicle_cache
insurance_vehicles
integration_webhooks
integration_workflows
internal_event_dedup
internal_sms_messages
join_requests
known_devices
kpi_daily_snapshots
link_previews
live_badges
live_chat_bans
live_chat_messages
live_collab_sessions
live_donations
live_locations
live_moderators
live_questions
live_schedule_reminders
live_session_analytics
live_sessions
live_shopping_pins
live_shopping_products
live_stream_reports
live_viewers
locations
login_events
media_objects
message_edit_history
message_polls
message_reactions
message_read_receipts
message_reminders
message_threads
message_versions
messages
metrics_registry
metrics_samples
mini_app_sessions
mini_apps
moderation_actions
moderation_appeals
moderation_cases
moderation_decisions
moderation_events
moderation_queue_items
moderation_reporter_quality
moderation_reports
music_library
music_playlist_tracks
music_playlists
music_tracks
nav_addresses
nav_crowdsource_reports
nav_demand_forecast
nav_dispatch_log
nav_dispatch_offers
nav_driver_profiles
nav_enforcement_actions
nav_geocoding_cache
nav_location_history
nav_location_history_default
nav_location_shares
nav_map_edits
nav_pois
nav_report_votes
nav_reporter_reputation
nav_risk_events
nav_risk_events_default
nav_risk_scores
nav_road_segments
nav_saved_places
nav_search_history
nav_surge_pricing
nav_traffic_segments
nav_traffic_segments_default
nav_trips
nav_zone_market_state
nav_zones
note_reactions
notification_category_settings
notification_deliveries
notification_events
notification_exceptions
notification_schedules
notification_settings
notifications
owner_escalation_requests
owners
paid_message_transactions
payment_invoices
payment_refunds
payout_requests
phone_otps
pinned_messages
pinned_posts
policy_renewals
poll_options
poll_votes
post_collabs
post_comments
post_content_tags
post_likes
post_media
post_people_tags
post_promotions
post_reminders
post_user_tags
post_views
posts
premium_features
premium_limits
premium_payments
premium_plans
premium_subscriptions
privacy_rule_exceptions
privacy_rules
product_reviews
product_tags
product_variants
profile_links
profile_notes
profiles
projection_watermarks
properties
property_favorites
property_images
property_saved_searches
property_views
publish_events
publish_outbox
push_tokens
quick_reaction_catalog
quick_replies
ranking_explanations
rate_limit_audits
rate_limit_configs
reaction_pack_items
reaction_packs
recommended_content
recommended_users
recovery_emails
reel_audio_tracks
reel_audios
reel_collaborators
reel_comment_likes
reel_comments
reel_content_features
reel_hashtags
reel_impressions
reel_likes
reel_metrics
reel_metrics_snapshots
reel_moderation_audit
reel_remixes
reel_reposts
reel_saves
reel_shares
reel_templates
reel_trending_topics
reel_views
reel_virality_metrics
reels
reels_engine_action_journal
reels_engine_config_versions
reels_engine_segment_state
render_job_logs
render_jobs
restricted_users
rights_events
risk_events
rollback_policies
rpc_audit_log
saved_collection_items
saved_collections
saved_messages
saved_posts
scheduled_messages
scope_definitions
scope_invites
search_history
secret_chats
sent_gifts
service_bugs
service_identities
service_keys
settings_change_audit
shared_locations
shop_cart_items
shop_collection_items
shop_collections
shop_order_items
shop_orders
shop_products
shops
similar_users
snapshot_content_hashes
spam_indicators
spatial_ref_sys
star_reactions
polls
star_transactions
sticker_items
sticker_packs
stickers
stories
story_countdown_subscribers
story_countdowns
story_emoji_slider_votes
story_emoji_sliders
story_highlights
story_music
story_poll_votes
story_polls
story_question_answers
story_questions
story_quiz_answers
story_quizzes
story_reactions
story_replies
story_segments
story_stickers
story_views
supergroup_member_permissions
supergroup_settings
taxi_complaints
taxi_driver_locations
taxi_driver_ratings
taxi_drivers
taxi_ratings
taxi_rides
taxi_scheduled_rides
taxi_surge_cache
telemetry_events
tenant_members
tenants
testimonials
thread_read_positions
threads_muted
transcode_jobs
transit_routes
translated_messages
trend_runs
trending_hashtags
trending_topics
trust_profiles
trust_weight_overrides
turn_issuance_audit
turn_issuance_rl
turn_replay_guard
upload_parts
uploads
user_app_icon_selection
user_appearance_settings
user_author_affinity
user_badges
user_channel_group_settings
user_chat_settings
user_consumption_diversity
user_dnd_settings
user_embeddings
user_emoji_packs
user_emoji_preferences
user_encryption_keys
user_energy_saver_settings
user_global_chat_settings
user_hidden_words
user_interactions
user_interests
user_locations
user_notes
user_prekey_bundles
user_quick_reaction
user_quick_reaction_overrides
user_reaction_packs
user_recent_stickers
user_reel_feedback
user_reel_interactions
user_roles
user_saved_gifs
user_saved_tracks
user_screen_time
user_security_settings
user_session_context
user_sessions
user_settings
user_similarity_scores
user_stars
user_status_notes
user_sticker_archive
user_sticker_library
user_sticker_packs
user_story_settings
user_totp_secrets
user_verifications
username_transactions
vanish_mode_sessions
verification_requests
video_call_signals
video_calls_legacy
video_messages
voice_messages`.trim().split('\n');

// Группировка
const groups = {};
for (const t of tables) {
  let group = 'other';

  if (t.startsWith('auth_')) group = 'auth';
  else if (t.startsWith('user_') || t === 'profiles') group = 'user';
  else if (t.startsWith('post_') || t === 'posts') group = 'posts';
  else if (t.startsWith('message_') || t === 'messages') group = 'messages';
  else if (t.startsWith('channel_') || t === 'channels') group = 'channels';
  else if (t.startsWith('group_chat') || t === 'group_chats') group = 'group_chats';
  else if (t.startsWith('story_') || t === 'stories') group = 'stories';
  else if (t.startsWith('comment_')) group = 'comments';
  else if (t.startsWith('reel_') || t === 'reels') group = 'reels';
  else if (t.startsWith('nav_')) group = 'navigation';
  else if (t.startsWith('taxi_')) group = 'taxi';
  else if (t.startsWith('live_')) group = 'live';
  else if (t.startsWith('insurance_')) group = 'insurance';
  else if (t.startsWith('shop_')) group = 'shop';
  else if (t.startsWith('music_') || t === 'music_library') group = 'music';
  else if (t.startsWith('editor_')) group = 'editor';
  else if (t.startsWith('creator_') || t.startsWith('star_')) group = 'creator';
  else if (t.startsWith('admin_')) group = 'admin';
  else if (t.startsWith('moderation_') || t.startsWith('content_')) group = 'moderation';
  else if (t.startsWith('bot_')) group = 'bots';
  else if (t.startsWith('email_')) group = 'email';
  else if (t.startsWith('notification_') || t === 'notifications') group = 'notifications';
  else if (t.startsWith('payment_') || t.startsWith('premium_')) group = 'payments';
  else if (t.startsWith('video_call') || t.startsWith('audio_')) group = 'calls';
  else if (t.startsWith('hashtag') || t.startsWith('trending') || t.startsWith('explore') || t.startsWith('search')) group = 'discovery';
  else if (t.startsWith('follow') || t.startsWith('block') || t.startsWith('close_friend')) group = 'social';
  else if (t.startsWith('privacy_') || t.startsWith('encryption')) group = 'security';
  else if (t.startsWith('idempotency') || t.startsWith('rate_limit')) group = 'infra';
  else if (t.startsWith('ab_')) group = 'experiments';
  else if (t.startsWith('ai_')) group = 'ai';
  else if (t.startsWith('anti_abuse') || t.startsWith('spam')) group = 'moderation';

  if (!groups[group]) groups[group] = [];
  groups[group].push(t);
}

// Вывод
const sortedGroups = Object.entries(groups).sort((a, b) => b[1].length - a[1].length);
for (const [group, tbls] of sortedGroups) {
  const files = Math.ceil(tbls.length / 10);
  console.log(`## ${group} (${tbls.length} tables, ~${files} files)`);
  for (let i = 0; i < tbls.length; i += 10) {
    console.log('  ' + tbls.slice(i, i+10).join(', '));
  }
  console.log('');
}
