import type { Tariff, FavoriteAddress, SurgeZone, VehicleClass } from '@/types/taxi';

// === Тарифы ===
export const TARIFFS: Tariff[] = [
  {
    id: 'economy',
    name: 'Эконом',
    description: 'Бюджетные поездки',
    emoji: '🚗',
    capacity: 4,
    basePrice: 69,
    pricePerKm: 18,
    pricePerMin: 3.5,
    minPrice: 150,
    eta: 4,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Кондиционер'],
    badge: 'Популярный',
  },
  {
    id: 'comfort',
    name: 'Комфорт',
    description: 'Просторный, хорошо оборудованный',
    emoji: '🚙',
    capacity: 4,
    basePrice: 99,
    pricePerKm: 25,
    pricePerMin: 5,
    minPrice: 250,
    eta: 5,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Кондиционер', 'Зарядка', 'Тихая поездка'],
  },
  {
    id: 'business',
    name: 'Бизнес',
    description: 'Премиум-автомобили',
    emoji: '🏎️',
    capacity: 4,
    basePrice: 199,
    pricePerKm: 45,
    pricePerMin: 9,
    minPrice: 500,
    eta: 7,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Кондиционер', 'Зарядка', 'Wi-Fi', 'Вода'],
  },
  {
    id: 'minivan',
    name: 'Минивэн',
    description: 'До 6 пассажиров',
    emoji: '🚐',
    capacity: 6,
    basePrice: 149,
    pricePerKm: 35,
    pricePerMin: 6,
    minPrice: 400,
    eta: 8,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Кондиционер', 'Большой багажник'],
  },
  {
    id: 'premium',
    name: 'Премиум',
    description: 'Luxury автомобили',
    emoji: '✨',
    capacity: 4,
    basePrice: 350,
    pricePerKm: 70,
    pricePerMin: 15,
    minPrice: 1000,
    eta: 10,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Премиум авто', 'Кондиционер', 'Wi-Fi', 'Вода', 'Газеты'],
  },
  {
    id: 'kids',
    name: 'Детский',
    description: 'Детское кресло',
    emoji: '👶',
    capacity: 3,
    basePrice: 99,
    pricePerKm: 27,
    pricePerMin: 5.5,
    minPrice: 300,
    eta: 8,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Детское кресло', 'Кондиционер'],
    badge: 'С креслом',
  },
  {
    id: 'green',
    name: 'Эко',
    description: 'Электромобили',
    emoji: '🌿',
    capacity: 4,
    basePrice: 89,
    pricePerKm: 22,
    pricePerMin: 4.5,
    minPrice: 200,
    eta: 9,
    surgeMultiplier: 1.0,
    available: true,
    features: ['Электромобиль', 'Кондиционер', 'Зарядка'],
    badge: 'Эко',
  },
];

// === Стандартные избранные адреса (пустые, заполняются пользователем) ===
export const DEFAULT_FAVORITE_ADDRESSES: FavoriteAddress[] = [
  {
    id: 'home',
    type: 'home',
    label: 'Дом',
    address: '',
    coordinates: { lat: 0, lng: 0 },
    icon: '🏠',
  },
  {
    id: 'work',
    type: 'work',
    label: 'Работа',
    address: '',
    coordinates: { lat: 0, lng: 0 },
    icon: '💼',
  },
];

// === Зоны surge — Москва ===
export const SURGE_ZONES: SurgeZone[] = [
  {
    id: 'center',
    center: { lat: 55.7558, lng: 37.6173 },
    radiusKm: 3,
    multiplier: 1.4,
    label: 'Центр Москвы',
  },
  {
    id: 'vnukovo',
    center: { lat: 55.5975, lng: 37.2659 },
    radiusKm: 2,
    multiplier: 1.2,
    label: 'Внуково',
  },
  {
    id: 'sheremetyevo',
    center: { lat: 55.9727, lng: 37.4146 },
    radiusKm: 2,
    multiplier: 1.3,
    label: 'Шереметьево',
  },
];

// === Mock адреса Москвы для автокомплита ===
export const MOCK_ADDRESS_SUGGESTIONS = [
  {
    id: '1',
    address: 'Москва, Красная площадь',
    shortAddress: 'Красная площадь',
    coordinates: { lat: 55.7539, lng: 37.6208 },
    type: 'place' as const,
    icon: '🏛️',
  },
  {
    id: '2',
    address: 'Москва, Арбат, 4',
    shortAddress: 'Арбат',
    coordinates: { lat: 55.7518, lng: 37.5964 },
    type: 'address' as const,
  },
  {
    id: '3',
    address: 'Москва, Садовая-Кольцевая ул., 5',
    shortAddress: 'Садовое кольцо',
    coordinates: { lat: 55.7631, lng: 37.6038 },
    type: 'address' as const,
  },
  {
    id: '4',
    address: 'Аэропорт Шереметьево (SVO)',
    shortAddress: 'Шереметьево',
    coordinates: { lat: 55.9727, lng: 37.4146 },
    type: 'place' as const,
    icon: '✈️',
  },
  {
    id: '5',
    address: 'Аэропорт Внуково (VKO)',
    shortAddress: 'Внуково',
    coordinates: { lat: 55.5975, lng: 37.2659 },
    type: 'place' as const,
    icon: '✈️',
  },
  {
    id: '6',
    address: 'Аэропорт Домодедово (DME)',
    shortAddress: 'Домодедово',
    coordinates: { lat: 55.4102, lng: 37.8997 },
    type: 'place' as const,
    icon: '✈️',
  },
  {
    id: '7',
    address: 'Москва, Ленинградский проспект, 37',
    shortAddress: 'Ленинградский пр.',
    coordinates: { lat: 55.7929, lng: 37.5377 },
    type: 'address' as const,
  },
  {
    id: '8',
    address: 'Москва, ЦУМ, Петровка, 2',
    shortAddress: 'ЦУМ',
    coordinates: { lat: 55.7604, lng: 37.6189 },
    type: 'place' as const,
    icon: '🛍️',
  },
  {
    id: '9',
    address: 'Москва, Лубянская площадь, 2',
    shortAddress: 'Лубянка',
    coordinates: { lat: 55.7588, lng: 37.6262 },
    type: 'address' as const,
  },
  {
    id: '10',
    address: 'Москва, ВДНХ',
    shortAddress: 'ВДНХ',
    coordinates: { lat: 55.8204, lng: 37.6402 },
    type: 'place' as const,
    icon: '🎡',
  },
  {
    id: '11',
    address: 'Москва, Тверская улица, 1',
    shortAddress: 'Тверская',
    coordinates: { lat: 55.7621, lng: 37.6115 },
    type: 'address' as const,
  },
  {
    id: '12',
    address: 'Москва, Тверская улица, 7',
    shortAddress: 'Тверская, 7',
    coordinates: { lat: 55.7641, lng: 37.6065 },
    type: 'address' as const,
  },
  {
    id: '13',
    address: 'Москва, Тверская улица, 12',
    shortAddress: 'Тверская, 12',
    coordinates: { lat: 55.7655, lng: 37.6028 },
    type: 'address' as const,
  },
  {
    id: '14',
    address: 'Москва, Пушкинская площадь',
    shortAddress: 'Пушкинская пл.',
    coordinates: { lat: 55.7655, lng: 37.6044 },
    type: 'place' as const,
    icon: '📍',
  },
  {
    id: '15',
    address: 'Москва, Новый Арбат, 11',
    shortAddress: 'Новый Арбат',
    coordinates: { lat: 55.752, lng: 37.589 },
    type: 'address' as const,
  },
  {
    id: '16',
    address: 'Москва, Патриаршие пруды',
    shortAddress: 'Патриаршие',
    coordinates: { lat: 55.7644, lng: 37.5929 },
    type: 'place' as const,
    icon: '🏞️',
  },
  {
    id: '17',
    address: 'ТЦ Охотный Ряд, Манежная площадь',
    shortAddress: 'Охотный Ряд',
    coordinates: { lat: 55.7554, lng: 37.6149 },
    type: 'place' as const,
    icon: '🛍️',
  },
  {
    id: '18',
    address: 'Москва, Замоскворечье, Пятницкая ул., 1',
    shortAddress: 'Пятницкая',
    coordinates: { lat: 55.7434, lng: 37.6276 },
    type: 'address' as const,
  },
  {
    id: '19',
    address: 'Москва, Кутузовский проспект, 2/1',
    shortAddress: 'Кутузовский пр.',
    coordinates: { lat: 55.7467, lng: 37.5639 },
    type: 'address' as const,
  },
  {
    id: '20',
    address: 'Москва, Покровка, 27',
    shortAddress: 'Покровка',
    coordinates: { lat: 55.7578, lng: 37.6458 },
    type: 'address' as const,
  },
  {
    id: '21',
    address: 'Москва, ст. метро Таганская',
    shortAddress: 'Таганская',
    coordinates: { lat: 55.7399, lng: 37.6527 },
    type: 'place' as const,
    icon: '🚇',
  },
  {
    id: '22',
    address: 'Москва, ст. метро Курская',
    shortAddress: 'Курская',
    coordinates: { lat: 55.7574, lng: 37.6593 },
    type: 'place' as const,
    icon: '🚇',
  },
  {
    id: '23',
    address: 'Москва, ст. метро Белорусская',
    shortAddress: 'Белорусская',
    coordinates: { lat: 55.776, lng: 37.5806 },
    type: 'place' as const,
    icon: '🚇',
  },
  {
    id: '24',
    address: 'Москва, ст. метро Киевская',
    shortAddress: 'Киевская',
    coordinates: { lat: 55.744, lng: 37.5657 },
    type: 'place' as const,
    icon: '🚇',
  },
  {
    id: '25',
    address: 'Москва, Красносельская, 2-й Красносельский пер.',
    shortAddress: 'Красносельская',
    coordinates: { lat: 55.7793, lng: 37.6545 },
    type: 'address' as const,
  },
  {
    id: '26',
    address: 'Парк Горького, ул. Крымский Вал, 9',
    shortAddress: 'Парк Горького',
    coordinates: { lat: 55.7307, lng: 37.6022 },
    type: 'place' as const,
    icon: '🌳',
  },
  {
    id: '27',
    address: 'Москва, Садовая-Самотёчная ул., 1',
    shortAddress: 'Садовая-Самотёчная',
    coordinates: { lat: 55.769, lng: 37.6088 },
    type: 'address' as const,
  },
  {
    id: '28',
    address: 'ТЦ Европейский, площадь Киевского вокзала, 2',
    shortAddress: 'ТЦ Европейский',
    coordinates: { lat: 55.743, lng: 37.5663 },
    type: 'place' as const,
    icon: '🛍️',
  },
  {
    id: '29',
    address: 'Москва, Чистые пруды, Чистопрудный б-р',
    shortAddress: 'Чистые пруды',
    coordinates: { lat: 55.7615, lng: 37.6408 },
    type: 'place' as const,
    icon: '🏞️',
  },
  {
    id: '30',
    address: 'Москва, Бауманская ул., 32',
    shortAddress: 'Бауманская',
    coordinates: { lat: 55.7713, lng: 37.6787 },
    type: 'address' as const,
  },
];

// === Центр карты по умолчанию ===
export const DEFAULT_MAP_CENTER = { lat: 55.7558, lng: 37.6173 };
export const DEFAULT_MAP_ZOOM = 14;

// === Цвета тарифов ===
export const TARIFF_COLORS: Record<VehicleClass, string> = {
  economy: '#6366f1',
  comfort: '#8b5cf6',
  business: '#2563eb',
  minivan: '#0891b2',
  premium: '#b45309',
  kids: '#16a34a',
  green: '#15803d',
};

// === Время ожидания водителя (бесплатно) в минутах ===
export const FREE_WAITING_MINUTES = 5;

// === Стоимость ожидания сверх лимита (за минуту) ===
export const OVERTIME_WAITING_PRICE_PER_MIN = 5;

// === Минимальное время принятия заказа водителем ===
export const DRIVER_ACCEPTANCE_TIMEOUT_SECONDS = 15;

// === Интервал обновления позиции водителя ===
export const DRIVER_LOCATION_UPDATE_INTERVAL_MS = 3000;
