-- Phase 1 L1.1: Tenant Model + Auto-Creation (Telegram-grade)
CREATE TABLE tenants(tenant_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','suspended','deleted')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE tenant_members(tenant_id UUID NOT NULL REFERENCES tenants(tenant_id)ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES auth.users(id)ON DELETE CASCADE,role TEXT NOT NULL DEFAULT'member'CHECK(role IN('owner','admin','member','guest')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,user_id));
CREATE INDEX tenant_members_user_id_idx ON tenant_members(user_id);
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;ALTER TABLE tenant_members ENABLE ROW LEVEL SECURITY;
REVOKE INSERT,UPDATE,DELETE ON tenants FROM anon,authenticated;REVOKE INSERT,UPDATE,DELETE ON tenant_members FROM anon,authenticated;
GRANT SELECT ON tenants TO authenticated;GRANT SELECT ON tenant_members TO authenticated;
CREATE POLICY tenants_read ON tenants FOR SELECT TO authenticated USING(tenant_id IN(SELECT tm.tenant_id FROM tenant_members tm WHERE tm.user_id=auth.uid()));
CREATE POLICY tenant_members_read ON tenant_members FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE OR REPLACE FUNCTION assert_actor_context_v1(p_auth_context JSONB)RETURNS VOID LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$ BEGIN IF p_auth_context IS NULL OR p_auth_context='{}'::JSONB THEN RAISE EXCEPTION'auth_context_required'USING ERRCODE='P0019';END IF;IF(p_auth_context->>'user_id')IS NULL THEN RAISE EXCEPTION'auth_context_missing_user_id'USING ERRCODE='P0019';END IF;END;$$;
CREATE OR REPLACE FUNCTION get_user_tenant_id_v1(p_user_id UUID DEFAULT NULL)RETURNS UUID LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$ DECLARE v_tenant_id UUID;v_uid UUID;BEGIN v_uid:=COALESCE(p_user_id,auth.uid());SELECT tenant_id INTO v_tenant_id FROM tenant_members WHERE user_id=v_uid LIMIT 1;RETURN v_tenant_id;END;$$;
CREATE OR REPLACE FUNCTION assert_tenant_member_v1(p_tenant_id UUID,p_min_role TEXT DEFAULT'member')RETURNS VOID LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$ DECLARE v_role TEXT;v_role_priority INT;v_min_priority INT;BEGIN IF p_tenant_id IS NULL THEN RAISE EXCEPTION'tenant_required'USING ERRCODE='P0001';END IF;SELECT role INTO v_role FROM tenant_members WHERE tenant_id=p_tenant_id AND user_id=auth.uid();IF v_role IS NULL THEN RAISE EXCEPTION'not_tenant_member'USING ERRCODE='P0002';END IF;v_role_priority:=CASE v_role WHEN'owner'THEN 4 WHEN'admin'THEN 3 WHEN'member'THEN 2 WHEN'guest'THEN 1 ELSE 0 END;v_min_priority:=CASE p_min_role WHEN'owner'THEN 4 WHEN'admin'THEN 3 WHEN'MEMBER'THEN 2 WHEN'guest'THEN 1 ELSE 0 END;IF v_role_priority<v_min_priority THEN RAISE EXCEPTION'insufficient_tenant_role'USING ERRCODE='P0003';END IF;END;$$;
CREATE OR REPLACE FUNCTION auto_create_personal_tenant_v1()RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE v_tenant_id UUID;v_display_name TEXT;BEGIN v_display_name:=COALESCE(NEW.raw_user_meta_data->>'full_name',NEW.raw_user_meta_data->>'name',split_part(NEW.email,'@',1));INSERT INTO tenants(name,status)VALUES(v_display_name||'''s Workspace','active')RETURNING tenant_id INTO v_tenant_id;INSERT INTO tenant_members(tenant_id,user_id,role)VALUES(v_tenant_id,NEW.id,'owner');RETURN NEW;END;$$;
CREATE TRIGGER auto_create_tenant_on_signup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION auto_create_personal_tenant_v1();
CREATE OR REPLACE FUNCTION update_updated_at_column()RETURNS TRIGGER AS $$ BEGIN NEW.updated_at=now();RETURN NEW;END;$$ LANGUAGE plpgsql;
CREATE TRIGGER tenants_updated_at BEFORE UPDATE ON tenants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER tenant_members_updated_at BEFORE UPDATE ON tenant_members FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
