// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createFetchWithTimeout } from "@/lib/network/fetchWithTimeout";

function normalizeEnv(value: unknown): string {
  if (typeof value !== "string") return "";
  // GitHub Secrets / .env values are sometimes pasted with surrounding quotes.
  // Supabase rejects API keys that include extra quotes/whitespace.
  return value
    .trim()
    .replace(/^["']+|["']+$/g, "")
    // In some terminals/clipboards JWTs are copied with line breaks.
    // Remove all whitespace characters to get a valid base64url token.
    .replace(/\s+/g, "");
}

function normalizeSupabaseKey(value: unknown): string {
  // Keys should not contain whitespace; removing it makes the app resilient to wrapped/copy-pasted JWTs.
  return normalizeEnv(value).replace(/\s+/g, "");
}

const SUPABASE_URL = normalizeEnv(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = normalizeSupabaseKey(
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY,
);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createFetchWithTimeout({ timeoutMs: 45_000 }), // Increased from 15s to 45s for slow functions
  },
  auth: {
    storage: localStorage,
    // Multi-account: persistence is handled by our Account Vault.
    // Active session is restored deterministically on app start.
    persistSession: false,
    autoRefreshToken: true,
  }
});