// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createFetchWithTimeout } from "@/lib/network/fetchWithTimeout";
import { getSupabaseRuntimeConfig } from "@/lib/supabaseRuntimeConfig";
import { logger } from "@/lib/logger";

function normalizeEnv(value: unknown): string {
  if (typeof value !== "string") return "";
  // GitHub Secrets / .env values are sometimes pasted with surrounding quotes.
  // Supabase rejects API keys that include extra quotes/whitespace.
  return value
    .trim()
    .replace(/^["']+|["']+$/g, "")
    // In some terminals/clipboards JWTs are copied with line breaks.
    // Remove all whitespace characters to get a valid base64url token.
    .replace(/\s+/g, "");
}

function normalizeSupabaseKey(value: unknown): string {
  // Keys should not contain whitespace; removing it makes the app resilient to wrapped/copy-pasted JWTs.
  return normalizeEnv(value).replace(/\s+/g, "");
}

const runtimeConfig = getSupabaseRuntimeConfig();
const SUPABASE_URL = normalizeEnv(runtimeConfig.supabaseUrl);
const SUPABASE_PUBLISHABLE_KEY = normalizeSupabaseKey(runtimeConfig.supabasePublishableKey);
const DEMO_MODE = runtimeConfig.demoMode;

function extractProjectRefFromUrl(url: string): string | null {
  const m = String(url || "").trim().match(/^https?:\/\/([a-z0-9-]+)\.supabase\.co\/?/i);
  return m?.[1] ? String(m[1]) : null;
}

function enforceExpectedProjectRef() {
  // Build-time env lock: prevents shipping a bundle that points to a different Supabase project.
  // This is intentionally strict in production builds.
  const expected = normalizeEnv(import.meta.env?.VITE_EXPECTED_SUPABASE_PROJECT_REF);
  if (!expected) return;

  const actual = extractProjectRefFromUrl(SUPABASE_URL);
  if (actual && expected && actual !== expected) {
    throw new Error(`SUPABASE_PROJECT_MISMATCH expected=${expected} actual=${actual}`);
  }
}

if (!import.meta.env.DEV) {
  enforceExpectedProjectRef();
}

if (import.meta.env.DEV) {
  const projectRef = extractProjectRefFromUrl(SUPABASE_URL);
  const anonPrefix = SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.slice(0, 8) : "";
  logger.info("[Env] Supabase", {
    VITE_SUPABASE_URL: SUPABASE_URL,
    projectRef,
    anonKeyPrefix: anonPrefix,
    demoMode: DEMO_MODE,
  });
}

// Demo mode mock auth state
type DemoSession = {
  user: { id: string; email: string; user_metadata: Record<string, unknown> };
  access_token: string;
  refresh_token: string;
  expires_at: number;
};

const demoSessionStorageKey = "demo:auth:session";

function createDemoClient(): SupabaseClient {
  // Generate a stable demo user ID
  const deviceId = (() => {
    const stored = localStorage.getItem("demo:device:id");
    if (stored) return stored;
    const id = `demo-user-${Math.random().toString(36).slice(2, 10)}`;
    localStorage.setItem("demo:device:id", id);
    return id;
  })();

  // Create a mock session that mimics real Supabase session structure
  const getDemoSession = (): DemoSession | null => {
    const stored = localStorage.getItem(demoSessionStorageKey);
    if (!stored) return null;
    try {
      return JSON.parse(stored) as DemoSession;
    } catch {
      return null;
    }
  };

  const setDemoSession = (session: DemoSession | null) => {
    if (session) {
      localStorage.setItem(demoSessionStorageKey, JSON.stringify(session));
    } else {
      localStorage.removeItem(demoSessionStorageKey);
    }
  };

  // Mock auth object
  const mockAuth = {
    getSession: async () => {
      const session = getDemoSession();
      return { data: { session } };
    },
    signInWithPassword: async ({ email }: { email: string; password: string }) => {
      const now = Math.floor(Date.now() / 1000);
      const session: DemoSession = {
        user: { id: deviceId, email, user_metadata: { full_name: email.split("@")[0] || "Demo User" } },
        access_token: `demo-access-${deviceId}`,
        refresh_token: `demo-refresh-${deviceId}`,
        expires_at: now + 3600,
      };
      setDemoSession(session);
      return { data: { session, user: session.user } };
    },
    signUp: async ({ email, password, options }: { email: string; password: string; options?: { data?: Record<string, unknown> } }) => {
      const now = Math.floor(Date.now() / 1000);
      const session: DemoSession = {
        user: { id: deviceId, email, user_metadata: { full_name: (options?.data?.full_name as string) || email.split("@")[0] || "Demo User" } },
        access_token: `demo-access-${deviceId}`,
        refresh_token: `demo-refresh-${deviceId}`,
        expires_at: now + 3600,
      };
      setDemoSession(session);
      return { data: { session, user: session.user } };
    },
    signInWithOtp: async ({ email }: { email: string }) => ({ data: {}, error: null }),
    verifyOtp: async ({ email }: { email: string; token: string; type: string }) => {
      const now = Math.floor(Date.now() / 1000);
      const session: DemoSession = {
        user: { id: deviceId, email, user_metadata: { full_name: email.split("@")[0] || "Demo User" } },
        access_token: `demo-access-${deviceId}`,
        refresh_token: `demo-refresh-${deviceId}`,
        expires_at: now + 3600,
      };
      setDemoSession(session);
      return { data: { session, user: session.user } };
    },
    signOut: async () => {
      setDemoSession(null);
      return { error: null };
    },
    updateUser: async ({ data }: { data: Record<string, unknown> }) => {
      const session = getDemoSession();
      if (session) {
        session.user.user_metadata = { ...session.user.user_metadata, ...data };
        setDemoSession(session);
      }
      return { data: { user: session?.user }, error: null };
    },
    onAuthStateChange: (_callback: (event: string, session: DemoSession | null) => void) => {
      const session = getDemoSession();
      _callback(session ? "INITIAL_SESSION" : "SIGNED_OUT", session);
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
    refreshSession: async () => {
      const session = getDemoSession();
      return { data: { session } };
    },
  };

  // Mock from() for database queries - in-memory storage
  const demoTables = new Map<string, Map<string, unknown>>();

  const mockFrom = (tableName: string) => ({
    select: (_cols: string) => ({
      eq: (_col: string, value: string) => ({
        maybeSingle: async () => {
          const table = demoTables.get(tableName);
          if (!table) return { data: null, error: null };
          const row = table.get(value);
          return { data: row || null, error: null };
        },
        single: async () => {
          const table = demoTables.get(tableName);
          if (!table) return { data: null, error: { message: "Table not found" } };
          const row = table.get(value);
          if (!row) return { data: null, error: { message: "Row not found" } };
          return { data: row, error: null };
        },
      }),
      maybeSingle: async () => ({ data: null, error: null }),
    }),
    upsert: (data: Record<string, unknown>) => ({
      onConflict: (_: string) => ({
        ignoreDuplicates: true,
        select: async () => ({ data, error: null }),
      }),
    }),
    insert: (_data: Record<string, unknown>) => ({
      select: async () => ({ data: [], error: null }),
    }),
  });

  const mockRpc = async (fnName: string, _params: Record<string, unknown>) => {
    // Return mock data for known RPCs used in demo mode
    if (fnName === "get_ranked_feed_v2") {
      return { data: [], error: null };
    }
    return { data: null, error: null };
  };

  const mockFunctions = {
    invoke: async (_fnName: string, _options?: Record<string, unknown>) => {
      // Return mock data for demo mode
      return { data: { ok: true }, error: null };
    },
  };

  const mockChannel = () => ({
    on: () => ({ subscribe: () => {} }),
    subscribe: () => ({ unsubscribe: () => {} }),
  });

  const mockRemoveAllChannels = () => {};

  return {
    auth: mockAuth,
    from: mockFrom,
    rpc: mockRpc,
    functions: mockFunctions,
    channel: mockChannel,
    removeAllChannels: mockRemoveAllChannels,
  } as unknown as SupabaseClient;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase: SupabaseClient;

if (DEMO_MODE) {
  logger.info("[Supabase] Using demo mode - no backend connection required");
  supabase = createDemoClient();
} else {
  // Real Supabase client
  const baseSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createFetchWithTimeout({ timeoutMs: 45_000 }), // Increased from 15s to 45s for slow functions
    },
    auth: {
      storage: localStorage,
      // Persist the *active* session on this device until explicit sign-out.
      // Multi-account still uses the Vault for additional accounts.
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  function isRetryableError(error: unknown): boolean {
    const errObj = error as Record<string, unknown> | null;
    const message = String(errObj?.message ?? "").toLowerCase();
    const code = String(errObj?.code ?? "").toLowerCase();
    return (
      message.includes("fetch") ||
      message.includes("network") ||
      message.includes("timeout") ||
      code === "ecconnreset" ||
      code === "etimedout"
    );
  }

  function withDefaultInvokeHeaders(options?: Record<string, unknown>): Record<string, unknown> | undefined {
    if (!SUPABASE_PUBLISHABLE_KEY) return options;

    const next: Record<string, unknown> = { ...(options ?? {}) };
    const headers = new Headers((options?.headers as HeadersInit | undefined) ?? undefined);

    if (!headers.has("apikey")) {
      headers.set("apikey", SUPABASE_PUBLISHABLE_KEY);
    }

    next.headers = Object.fromEntries(headers.entries());
    return next;
  }

  async function invokeWithRetry(fnName: string, options?: Record<string, unknown>) {
    const preparedOptions = withDefaultInvokeHeaders(options);
    const first = await baseSupabase.functions.invoke(fnName, preparedOptions as Parameters<typeof baseSupabase.functions.invoke>[1]);
    if (!first?.error) return first;
    if (!isRetryableError(first.error)) return first;

    const second = await baseSupabase.functions.invoke(fnName, preparedOptions as Parameters<typeof baseSupabase.functions.invoke>[1]);
    if (second?.error && import.meta.env.DEV) {
      logger.warn("[BackendBridge] functions.invoke failed after retry", {
        fnName,
        firstError: first.error,
        secondError: second.error,
      });
    }
    return second;
  }

  const functionsProxy = new Proxy(baseSupabase.functions, {
    get(target, prop, receiver) {
      if (prop === "invoke") {
        return invokeWithRetry;
      }
      const value = Reflect.get(target, prop, receiver);
      return typeof value === "function" ? value.bind(target) : value;
    },
  });

  const supabaseProxy = new Proxy(baseSupabase, {
    get(target, prop, receiver) {
      if (prop === "functions") {
        return functionsProxy;
      }
      const value = Reflect.get(target, prop, receiver);
      return typeof value === "function" ? value.bind(target) : value;
    },
  });

  supabase = supabaseProxy as typeof baseSupabase;
}

export { supabase };