export interface KaskoFormData {
  lastName: string;
  firstName: string;
  middleName: string;
  birthDate: string;
  passportSeries: string;
  passportNumber: string;
  passportIssued: string;
  passportDate: string;
  phone: string;
  email: string;
  address: string;
  make: string;
  model: string;
  year: string;
  vin: string;
  regNumber: string;
  enginePower: string;
  vehicleType: string;
  ptsSeries: string;
  ptsNumber: string;
  stsSeries: string;
  stsNumber: string;
  carValue: string;
  mileage: string;
  color: string;
  hasExtraEquipment: boolean;
  extraEquipmentDesc: string;
  coverageType: string;
  franchise: string;
  antiTheft: string;
  parkingType: string;
  hasPrevPolicy: boolean;
  prevCompany: string;
  hasLosses: boolean;
  lossesDesc: string;
  hasGap: boolean;
  hasKeyless: boolean;
  hasTowing: boolean;
  hasCommissioner: boolean;
  hasReplacement: boolean;
}

export function createDefaultKaskoFormData(): KaskoFormData {
  return {
    lastName: "",
    firstName: "",
    middleName: "",
    birthDate: "",
    passportSeries: "",
    passportNumber: "",
    passportIssued: "",
    passportDate: "",
    phone: "",
    email: "",
    address: "",
    make: "",
    model: "",
    year: "",
    vin: "",
    regNumber: "",
    enginePower: "",
    vehicleType: "",
    ptsSeries: "",
    ptsNumber: "",
    stsSeries: "",
    stsNumber: "",
    carValue: "",
    mileage: "",
    color: "",
    hasExtraEquipment: false,
    extraEquipmentDesc: "",
    coverageType: "full",
    franchise: "0",
    antiTheft: "none",
    parkingType: "garage",
    hasPrevPolicy: false,
    prevCompany: "",
    hasLosses: false,
    lossesDesc: "",
    hasGap: false,
    hasKeyless: false,
    hasTowing: false,
    hasCommissioner: false,
    hasReplacement: false,
  };
}
